server:
  port: 9001


#  回调网址必须是公网 所以要用内网穿透
alipay:
  appId: 2021000122679038
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCELZznNRQQmAjZB7dtWdl5LID6ELyWUYO2Cp+pmRDQWi0mTklJhS35nJhEZKsZtJ3/FQbi3128Wmmp1Qw4Af6G6mL10y075k8hG+wY0lPoS8Yoei5N9Lvxb/O+RLkYhcbqJCFtby3asnsg/FF+IQEIFS4i1wb2iyr49gVMhHg9gmQVWLGwn04IBXynhFTmGbaHIKxkryWE4FR4uYT+F8GYQQNNoRJBzQqhdcZnUIKQ9e2leflW9WLDE3M6kL808jc1hmX8a8auR0qKtSZTw3RGqbI97zuzedeb4mxovuig9OMqS+vyQxCSrLkjbrtBhcNiy5G6lXx8Y95HaDAsdhCjAgMBAAECggEAIjQneREcKxsclwTPK4Xnp9qjWZKBKqjXW4EuRdXtKu1a56G0h0jmV8R1BqXCPPmnNP389TJ18Cq5UxBlhAzID6ORjilieDCl41x1YQr0WZVaJtlPKC8ff1/IBEGGYFkl2ysUV1xA0moDQMrqT6g8uxm4AZ4BGEV1Dk2jm2RgNRIsgv1cddKthcZx8XxQL9SZlHcRGH5IgKlWuhJrCy8tuasQsbPcutQKUjXep3iIC/OrMEnzaIavw284UZOai+rwmsXfrPEAQF9IbDGV27254O2Yr2b+ylnsJZmKY5Yk5OLWjbwsASs9zImLoNr5SPULqbbv8XOF4MeLZL0QwRNueQKBgQDA0dHSJLsbMNnsawkb/ZuSxjA9EjagzsPdW81FYQxVrbaFXdeZLWyNSbR7qgrayV4mZD3NPeNmiKwu1EYIRMcqGRO8xSAPFwFyWhyKgj6xdY87t2rED1sXKbdkUvDqxGT0MaSBF/zrzbqTY2W2+4dq7RD61REZDZFI/9N++ZhxHwKBgQCvfQql1ajiXGqPYHrGPh24YVyNs00LUP2a0nS1JqJgDbsrKG5WJ2Z+ycQ1Fm/S2qmWrdP5dhnI/jvq25U85oPVXmgl4AzbkoKADoLPdEv2oPzaG9RF3eyRU2x/8Hsv4v8xm6vnlFGpahj8KB9yMqqpz8sEqcc9fnhPoD5HlyAb/QKBgQCbE+WiEsKdYtPSbl+cMINAL7+6Tny7JrCmxt+4Tg5illz2tHvjCYKFu+K5lxA12MCtNe/yszTCUWfSHg3ZNp/MPvD94LkhCcqzEsBjsc8EYN17FNB8sTD81yNVP9PdrWjYcViyLv3PFN5bDhVPbssB93qxkk23DY9s27xZIhs11wKBgEgxh7zbXgPpgwkC5t9BVJayrxG4Tpy2L+6OX+baQviDDZneoy2cPeUw+h/g4BX9UMElN8wrksYGGP4wYX/RUTDpCq1yM7fs2PT3g0b3D/0hE4Ri6HvppVXP3RXxB6yWlOeCpEC72rB4bljl5LHlOCJt0pZThhy9N5+CS7zF5ja9AoGAcHp9WK2m/gqj6xbxAj4/WuCDhutyZvORWlB8SJLee8g8mKL/MWCyf7RD7nq9UUguq2XEP+iSMo3fWwvjIjkvoa061Zo96WFlAWTJKbQC+p2uPk1MgDcoeYJ/FjgqyaH5afWgJlkvDW1KxaAdDfnaerP9WcETeIhnexyV1MNHX30=
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtUPlAMefIJcob6tiNpIW6Uoi6Pw/82ATFuBuJBz2qEW61W1MIPryXamd2Lp3VWteATldkOnpZZKDb8hW9IRyUzRfViVaJX/tcO4wHy+Gd+Hi6OAPPj/fR7VYZLTvu3ORkabZWpwPbd+RcO7vy+wRs/v5RuloAb+inJSPvdf1niPn5+PFZEC16spbvq7UbvXHk15VhdVwAEB/0SsWix1pNjteV7ceIWpo14PIRdFkFbeF4Ti8BHOj+Do2+RCgKnIxwW+Wm9BpLfglBbVdqbhl3Nz/o2lHA5hbUSUdONAv+EVPPZCNT9bj1Bha4yOT3CykeEU2dxEDRDjEatSjFmPueQIDAQAB
  notifyUrl: asd2828282.w3.luyouxia.net/alipay/notify


spring:
  application:
    name: service-pay
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
